development:
  trial_emails:
    class: Subscriptions::SendTrialEndedEmailsJob
    schedule: every day at 10:00am
  signals_scan:
    class: Signals::ScanAllJob
    schedule: every day at 6:00am

production:
  trial_emails:
    class: Subscriptions::SendTrialEndedEmailsJob
    schedule: every day at 10:00am
  signals_scan:
    class: Signals::ScanAllJob
    schedule: every day at 6:00am
